package platform

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"
)

func emitCC(t *testing.T, spec PipelineSpec) []PipelineArtifact {
	t.Helper()
	arts, err := ccPipelineProjector{}.Emit(spec)
	if err != nil {
		t.Fatalf("cc emit: %v", err)
	}
	return arts
}

// extractManifestJSON pulls the `export const MANIFEST = {…}` payload out of an
// emitted `.mjs` so a test can parse the generated stage table directly.
func extractManifestJSON(t *testing.T, content string) string {
	t.Helper()
	const prefix = "export const MANIFEST = "
	i := strings.Index(content, prefix)
	if i < 0 {
		t.Fatal("emitted mjs has no MANIFEST block")
	}
	rest := content[i+len(prefix):]
	end := strings.Index(rest, "\n// ======================= END GENERATED MANIFEST")
	if end < 0 {
		t.Fatal("emitted mjs manifest has no END banner")
	}
	return rest[:end]
}

func parseCCManifest(t *testing.T, content string) ccManifest {
	t.Helper()
	var m ccManifest
	if err := json.Unmarshal([]byte(extractManifestJSON(t, content)), &m); err != nil {
		t.Fatalf("manifest JSON does not parse: %v", err)
	}
	return m
}

// TestCCEmitStructureAndManifest is the fixture-IR → expected-manifest test: the
// skeleton spec must project the full per-task stage table (7 verify + 4 routine
// + cross-family) with the resolved model routes intact.
func TestCCEmitStructureAndManifest(t *testing.T) {
	arts := emitCC(t, skeletonSpec("/repo"))
	if len(arts) != 2 {
		t.Fatalf("want 2 artifacts, got %d", len(arts))
	}
	if arts[0].Name != CCPipelineArtifactName || arts[1].Name != CCReconcileArtifactName {
		t.Fatalf("artifact names = %q,%q", arts[0].Name, arts[1].Name)
	}
	pipeline := arts[0].Content
	assertCCGenerationHeader(t, pipeline)
	assertCCSkeletonManifest(t, parseCCManifest(t, pipeline))
	assertCCReconcileManifest(t, arts[1].Content)
}

// assertCCGenerationHeader checks the generation header and stable-runner banner.
func assertCCGenerationHeader(t *testing.T, pipeline string) {
	t.Helper()
	if !strings.HasPrefix(pipeline, "// generated by da workflow pipeline emit; do not hand-edit\n// config-digest: ") {
		t.Fatalf("pipeline missing generation header:\n%s", strings.SplitN(pipeline, "\n", 3))
	}
	if !strings.Contains(pipeline, ccStableRunnerMarker) {
		t.Fatal("pipeline missing stable runner banner")
	}
}

// assertCCSkeletonManifest checks the full per-task stage table (7 verify + 4
// routine + cross-family) with the resolved model routes and caps intact.
func assertCCSkeletonManifest(t *testing.T, m ccManifest) {
	t.Helper()
	if m.TargetCount != pipelineTargetCount {
		t.Fatalf("target_count = %d, want %d", m.TargetCount, pipelineTargetCount)
	}
	if m.Executor.Model != "claude-opus-4-8" || m.Executor.Family != "claude" {
		t.Fatalf("executor route = %+v", m.Executor)
	}
	if len(m.Verifiers) != maxPipelineVerifiers {
		t.Fatalf("verifiers = %d, want %d", len(m.Verifiers), maxPipelineVerifiers)
	}
	for i, v := range m.Verifiers {
		if v.Model != "claude-opus-4-8" || v.Family != "claude" {
			t.Fatalf("verifier[%d] route = %+v", i, v)
		}
	}
	if len(m.RoutineLenses) != maxPipelineRoutineLenses {
		t.Fatalf("routine lenses = %d, want %d", len(m.RoutineLenses), maxPipelineRoutineLenses)
	}
	assertCCCrossFamily(t, m)
	if m.Caps.MaxVerifiers != maxPipelineVerifiers || m.Caps.MaxRoutineLenses != maxPipelineRoutineLenses {
		t.Fatalf("caps = %+v", m.Caps)
	}
}

// assertCCCrossFamily checks the manifest cross-family binding (RULE-7): the
// NAMED slug, the resolved route, and a family that differs from the executor.
func assertCCCrossFamily(t *testing.T, m ccManifest) {
	t.Helper()
	if m.CrossFamily == nil {
		t.Fatal("skeleton must have a cross-family gate")
	}
	if m.CrossFamily.Slug != crossFamilyLensSlug {
		t.Fatalf("cross-family slug = %q, want %q", m.CrossFamily.Slug, crossFamilyLensSlug)
	}
	if m.CrossFamily.Model != "gpt-5.4" || m.CrossFamily.Family != "gpt" {
		t.Fatalf("cross-family route = %+v", m.CrossFamily)
	}
	if m.CrossFamily.Family == m.Executor.Family {
		t.Fatal("cross-family family must differ from executor (RULE-7)")
	}
	if m.CrossFamilySlug != crossFamilyLensSlug {
		t.Fatalf("manifest crossFamilySlug = %q", m.CrossFamilySlug)
	}
}

// assertCCReconcileManifest checks the app_type-agnostic reconcile artifact:
// executor route only, workspace, and the stamped config digest.
func assertCCReconcileManifest(t *testing.T, reconcile string) {
	t.Helper()
	var rm ccReconcileManifest
	if err := json.Unmarshal([]byte(extractManifestJSON(t, reconcile)), &rm); err != nil {
		t.Fatalf("reconcile manifest JSON does not parse: %v", err)
	}
	if rm.Model != "claude-opus-4-8" || rm.Family != "claude" || rm.Workspace != "/repo" {
		t.Fatalf("reconcile manifest = %+v", rm)
	}
	if rm.ConfigDigest != skeletonSpec("/repo").Digest() {
		t.Fatalf("reconcile digest = %q, want %q", rm.ConfigDigest, skeletonSpec("/repo").Digest())
	}
}

// TestCCEmitByteIdempotent proves the same spec re-emits byte-identical content
// and the digest is stamped in the header (no wall-clock).
func TestCCEmitByteIdempotent(t *testing.T) {
	a := emitCC(t, skeletonSpec("/repo"))
	b := emitCC(t, skeletonSpec("/repo"))
	for i := range a {
		if a[i].Content != b[i].Content {
			t.Fatalf("artifact %q is not byte-idempotent", a[i].Name)
		}
	}
	digest := skeletonSpec("/repo").Digest()
	if !strings.Contains(a[0].Content, "// config-digest: "+digest+"\n") {
		t.Fatalf("pipeline header missing digest %q", digest)
	}
}

// TestCCEmitSpecializedNaming checks app_type-qualified filenames and the
// specialized stage table (verifier_sequence slugs bound).
func TestCCEmitSpecializedNaming(t *testing.T) {
	spec, err := BuildPipelineSpec("/repo", "go-cli", fixtureStageProfiles(), fixtureExecProfile())
	if err != nil {
		t.Fatal(err)
	}
	arts := emitCC(t, spec)
	if arts[0].Name != "profile-pipeline.go-cli.mjs" || arts[1].Name != "profile-reconcile.go-cli.mjs" {
		t.Fatalf("specialized names = %q,%q", arts[0].Name, arts[1].Name)
	}
	m := parseCCManifest(t, arts[0].Content)
	if len(m.Verifiers) != 2 || m.Verifiers[0].Slug != "unit" || m.Verifiers[1].Slug != "cli-runner" {
		t.Fatalf("go-cli verifiers = %+v", m.Verifiers)
	}
	if m.AppType != "go-cli" {
		t.Fatalf("manifest app_type = %q", m.AppType)
	}
}

func TestCCArtifactName(t *testing.T) {
	cases := map[string]struct{ base, appType, want string }{
		"skeleton": {CCPipelineArtifactName, "", "profile-pipeline.mjs"},
		"apptype":  {CCPipelineArtifactName, "daemon", "profile-pipeline.daemon.mjs"},
		"slash":    {CCPipelineArtifactName, "docs/web", "profile-pipeline.docs-web.mjs"},
		"trim":     {CCReconcileArtifactName, "  meta  ", "profile-reconcile.meta.mjs"},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			if got := ccArtifactName(tc.base, tc.appType); got != tc.want {
				t.Fatalf("ccArtifactName(%q,%q) = %q, want %q", tc.base, tc.appType, got, tc.want)
			}
		})
	}
}

// TestCCEmitNoRoutineNoCrossFamily exercises the manifest branches where the
// routine lens group and/or the cross-family gate are absent: empty slices must
// render as `[]` and an absent cross-family as `null`.
func TestCCEmitNoRoutineNoCrossFamily(t *testing.T) {
	exec := StageRoute{Slug: "default", Model: "claude-opus-4-8", ModelFamily: "claude"}
	spec := PipelineSpec{
		Workspace:   "/repo",
		AppType:     "bare",
		TargetCount: 3,
		Executor:    exec,
		Verifiers:   []StageRoute{exec, exec},
	}
	content := emitCC(t, spec)[0].Content
	if !strings.Contains(content, "\"routineLenses\": []") {
		t.Fatal("empty routine lenses must render as []")
	}
	if !strings.Contains(content, "\"crossFamily\": null") {
		t.Fatal("absent cross-family must render as null")
	}
	m := parseCCManifest(t, content)
	if len(m.RoutineLenses) != 0 || m.CrossFamily != nil {
		t.Fatalf("manifest routine/cross = %+v / %+v", m.RoutineLenses, m.CrossFamily)
	}

	// Cross-family present but no routine lenses.
	cross := StageRoute{Slug: crossFamilyLensSlug, Model: "gpt-5.4", ModelFamily: "gpt"}
	spec.CrossFamily = &cross
	m2 := parseCCManifest(t, emitCC(t, spec)[0].Content)
	if m2.CrossFamily == nil || m2.CrossFamily.Slug != crossFamilyLensSlug {
		t.Fatalf("cross-family = %+v", m2.CrossFamily)
	}
}

// TestCCStableRunnerRegionIdentical proves the generated-vs-authored boundary:
// the STABLE RUNNER region (banner → EOF) is byte-identical across an unrelated
// skeleton and a specialized emit — only the header digest and MANIFEST differ.
func TestCCStableRunnerRegionIdentical(t *testing.T) {
	skeleton := emitCC(t, skeletonSpec("/repo"))
	spec, err := BuildPipelineSpec("/repo", "go-cli", fixtureStageProfiles(), fixtureExecProfile())
	if err != nil {
		t.Fatal(err)
	}
	special := emitCC(t, spec)

	runnerTail := func(content string) string {
		i := strings.Index(content, ccStableRunnerMarker)
		if i < 0 {
			t.Fatal("no stable runner marker")
		}
		return content[i:]
	}
	if runnerTail(skeleton[0].Content) != runnerTail(special[0].Content) {
		t.Fatal("pipeline stable runner region drifted between profiles")
	}
	if runnerTail(skeleton[1].Content) != runnerTail(special[1].Content) {
		t.Fatal("reconcile stable runner region drifted between profiles")
	}
}

// TestCCEmitRule7Refused confirms the projector refuses an invalid spec before
// any artifact is produced: a same-family cross lens (RULE-7) and an empty route.
func TestCCEmitRule7Refused(t *testing.T) {
	exec := StageRoute{Slug: "default", Model: "claude-opus-4-8", ModelFamily: "claude"}
	sameFamily := PipelineSpec{
		Workspace:   "/repo",
		TargetCount: 3,
		Executor:    exec,
		Verifiers:   []StageRoute{exec},
		CrossFamily: &StageRoute{Slug: crossFamilyLensSlug, Model: "claude-x", ModelFamily: "claude"},
	}
	if _, err := (ccPipelineProjector{}).Emit(sameFamily); err == nil || !strings.Contains(err.Error(), "must differ from executor family") {
		t.Fatalf("want RULE-7 refusal, got %v", err)
	}
	if _, err := (ccPipelineProjector{}).Emit(PipelineSpec{Workspace: ""}); err == nil {
		t.Fatal("emit should reject an invalid spec")
	}
}

func TestCCPlatformAndRuntimeDir(t *testing.T) {
	p := ccPipelineProjector{}
	if p.Platform() != "claude-code" {
		t.Fatalf("platform = %q", p.Platform())
	}
	if p.RuntimeRelDir() != filepath.Join(".claude", "workflows") {
		t.Fatalf("runtime dir = %q", p.RuntimeRelDir())
	}
}

func TestCCGeneratedHeaderReusesSharedMarker(t *testing.T) {
	got := ccGeneratedHeader("abc123")
	want := "// generated by da workflow pipeline emit; do not hand-edit\n// config-digest: abc123\n"
	if got != want {
		t.Fatalf("ccGeneratedHeader = %q, want %q", got, want)
	}
}

// stripTrailingReturn removes the single harness-only top-level `return {…}` so
// the emitted body parses as a real ES module (the ultracode-wave-engine test
// idiom). Node rejects a top-level return in a `.mjs`, so this must run before
// any `node --check` or import.
var ccTrailingReturn = regexp.MustCompile(`(?s)\nreturn \{.*\}\s*$`)

func stripTrailingReturn(content string) string {
	return ccTrailingReturn.ReplaceAllString(content, "\n")
}

// harnessEvalForm rewrites an emitted artifact into the form the Claude-Code
// workflow harness actually evaluates: the harness injects agent/parallel/... as
// globals, wraps the file body in an (async) function scope, and consumes the
// authored trailing top-level `return` as the run result (the ultracode-wave-engine
// idiom). A raw ES module rejects that top-level return and a bare function body
// rejects the module-level exports, so NEITHER raw form is node --check-clean by
// design. Mirroring the harness — strip the module-only `export` keywords and wrap
// the whole body (INCLUDING the trailing return) in an async function — yields the
// exact bytes the harness runs in a scope where they are legal, so node --check
// validates the real artifact, return and all.
func harnessEvalForm(content string) string {
	body := strings.ReplaceAll(content, "\nexport ", "\n")
	return "async function __wf__(args) {\n" + body + "\n}\n"
}

// TestCCEmittedMjsHarnessFormPassesNodeCheck validates each emitted artifact IN
// THE FORM THE HARNESS EVALUATES IT, not raw. Decision (documented here so no
// later reader mistakes the intent): the artifact deliberately follows the
// authored ultracode-wave-engine top-level-return idiom, so a RAW `node --check`
// fails by design and no artifact/header claims raw node-check validity. We
// instead node --check the harness-eval form (harnessEvalForm), which exercises
// the real artifact bytes — including the trailing return — in the injected
// function scope the harness runs them in. Skips when node is unavailable.
func TestCCEmittedMjsHarnessFormPassesNodeCheck(t *testing.T) {
	node := ccNode(t)
	dir := t.TempDir()
	for i, art := range emitCC(t, skeletonSpec("/repo")) {
		// The raw artifact is NOT node --check-clean (top-level return idiom);
		// validate the harness-eval form the CC harness actually evaluates.
		path := filepath.Join(dir, art.Name)
		if err := os.WriteFile(path, []byte(harnessEvalForm(art.Content)), 0o644); err != nil {
			t.Fatal(err)
		}
		if out, err := exec.Command(node, "--check", path).CombinedOutput(); err != nil {
			t.Fatalf("node --check (harness-eval form) failed for artifact %d (%s): %v\n%s", i, art.Name, err, out)
		}
	}
}

// TestCCRunnerExecutesUnderNode imports the stripped runner and exercises the
// stable helpers: stageSequence must materialize the exact stage ordering, and
// assertCrossFamily must throw on a same-family or mis-slugged cross lens
// (RULE-7 refusal on the JS side). Skips when node is unavailable.
func TestCCRunnerExecutesUnderNode(t *testing.T) {
	node := ccNode(t)
	dir, _ := ccStrippedModule(t)
	driver := filepath.Join(dir, "driver.mjs")
	driverSrc := "import { MANIFEST, stageSequence, assertCrossFamily } from './module.mjs'\n" +
		"const kinds = stageSequence(MANIFEST).map((s) => s.kind)\n" +
		"const caught = (fn) => { try { fn(); return false } catch { return true } }\n" +
		"const rule7Same = caught(() => assertCrossFamily({ crossFamilySlug: 'cross-harness-adversarial', executor: { family: 'claude' }, crossFamily: { slug: 'cross-harness-adversarial', family: 'claude' } }))\n" +
		"const rule7Slug = caught(() => assertCrossFamily({ crossFamilySlug: 'cross-harness-adversarial', executor: { family: 'claude' }, crossFamily: { slug: 'wrong', family: 'gpt' } }))\n" +
		"process.stdout.write(JSON.stringify({ kinds, rule7Same, rule7Slug }))\n"
	if err := os.WriteFile(driver, []byte(driverSrc), 0o644); err != nil {
		t.Fatal(err)
	}
	out, err := exec.Command(node, driver).CombinedOutput()
	if err != nil {
		t.Fatalf("node driver failed: %v\n%s", err, out)
	}
	var res struct {
		Kinds     []string `json:"kinds"`
		Rule7Same bool     `json:"rule7Same"`
		Rule7Slug bool     `json:"rule7Slug"`
	}
	if err := json.Unmarshal(out, &res); err != nil {
		t.Fatalf("driver output does not parse: %v\n%s", err, out)
	}
	// profile_resolve + executor + 7 verify + 4 routine + cross_family + gate.
	want := []string{"profile_resolve", "executor", "verify", "verify", "verify", "verify", "verify", "verify", "verify", "routine", "routine", "routine", "routine", "cross_family", "gate"}
	if strings.Join(res.Kinds, ",") != strings.Join(want, ",") {
		t.Fatalf("stage sequence = %v, want %v", res.Kinds, want)
	}
	if !res.Rule7Same {
		t.Fatal("assertCrossFamily must throw on a same-family cross lens (RULE-7)")
	}
	if !res.Rule7Slug {
		t.Fatal("assertCrossFamily must throw on a mis-slugged cross lens")
	}
}

// ccNode resolves the node binary or skips: every CC runner exercise validates
// the emitted JS against the real interpreter, never a mock of node itself.
func ccNode(t *testing.T) string {
	t.Helper()
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node not available; skipping runner exercise")
	}
	return node
}

// ccStrippedModule writes the emitted skeleton pipeline as an importable ES
// module (the harness-only trailing return removed) into a fresh temp dir and
// returns the dir plus the module path.
func ccStrippedModule(t *testing.T) (string, string) {
	t.Helper()
	dir := t.TempDir()
	module := filepath.Join(dir, "module.mjs")
	body := stripTrailingReturn(emitCC(t, skeletonSpec("/repo"))[0].Content)
	if err := os.WriteFile(module, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir, module
}

// ccMockResult is the driver-visible state a mock CC runner surfaces: the ordered
// agent labels that actually launched and the evidence gate's rendered prompt.
type ccMockResult struct {
	Labels     []string `json:"labels"`
	GatePrompt string   `json:"gatePrompt"`
}

// ccMockRun evaluates the emitted pipeline in the harness-eval form with mocked
// agent/parallel/phase/log globals, so the real runner-body gating logic runs
// under node. agentBody is the mock agent's return statement(s); the mock records
// every launched stage's label so the test can assert which stages were skipped.
func ccMockRun(t *testing.T, agentBody string) ccMockResult {
	t.Helper()
	node := ccNode(t)
	dir := t.TempDir()
	content := emitCC(t, skeletonSpec("/repo"))[0].Content
	driverSrc := "const calls = []\n" +
		"globalThis.phase = () => {}\n" +
		"globalThis.log = () => {}\n" +
		"globalThis.parallel = async (thunks) => Promise.all(thunks.map((fn) => fn()))\n" +
		"globalThis.agent = async (prompt, opts) => {\n" +
		"  const label = (opts && opts.label) || ''\n" +
		"  calls.push({ label, prompt })\n" +
		"  " + agentBody + "\n" +
		"}\n" +
		harnessEvalForm(content) +
		"\nawait __wf__({ task: 'T1' })\n" +
		"const gate = calls.find((c) => c.label === 'gate:T1')\n" +
		"process.stdout.write(JSON.stringify({ labels: calls.map((c) => c.label), gatePrompt: gate ? gate.prompt : '' }))\n"
	driver := filepath.Join(dir, "gating.mjs")
	if err := os.WriteFile(driver, []byte(driverSrc), 0o644); err != nil {
		t.Fatal(err)
	}
	out, err := exec.Command(node, driver).CombinedOutput()
	if err != nil {
		t.Fatalf("mock runner failed: %v\n%s", err, out)
	}
	var res ccMockResult
	if err := json.Unmarshal(out, &res); err != nil {
		t.Fatalf("mock runner output does not parse: %v\n%s", err, out)
	}
	return res
}

// TestCCParseVerdictUnderNode exercises the pure verdict parser: case-sensitive
// tokens, last-occurrence-wins, and FAIL-safe UNKNOWN for text naming no token.
func TestCCParseVerdictUnderNode(t *testing.T) {
	node := ccNode(t)
	dir, _ := ccStrippedModule(t)
	driver := filepath.Join(dir, "verdict.mjs")
	src := "import { parseVerdict } from './module.mjs'\n" +
		"process.stdout.write(JSON.stringify({\n" +
		"  lastWins: parseVerdict('slot checks PASS then FAIL'),\n" +
		"  rejectWins: parseVerdict('APPROVE early, REJECT late'),\n" +
		"  caseSensitive: parseVerdict('everything looks pass here'),\n" +
		"  noToken: parseVerdict('inconclusive run'),\n" +
		"  skip: parseVerdict('SKIP this slot'),\n" +
		"  nonString: parseVerdict(null),\n" +
		"}))\n"
	if err := os.WriteFile(driver, []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	out, err := exec.Command(node, driver).CombinedOutput()
	if err != nil {
		t.Fatalf("parseVerdict driver failed: %v\n%s", err, out)
	}
	var got map[string]string
	if err := json.Unmarshal(out, &got); err != nil {
		t.Fatalf("parseVerdict output does not parse: %v\n%s", err, out)
	}
	want := map[string]string{
		"lastWins":      "FAIL",
		"rejectWins":    "REJECT",
		"caseSensitive": "UNKNOWN",
		"noToken":       "UNKNOWN",
		"skip":          "SKIP",
		"nonString":     "UNKNOWN",
	}
	for k, w := range want {
		if got[k] != w {
			t.Fatalf("parseVerdict %s = %q, want %q", k, got[k], w)
		}
	}
}

// TestCCRunnerGatingUnderNode drives the real runner body with mocked agents to
// prove the S4-H7 gating contract: a verify FAIL short-circuits the remaining
// verify slots + routine + cross-family (the gate still runs with the FAIL in its
// serialized prompt), and a cross-family REJECT is recorded without skipping the
// gate.
func TestCCRunnerGatingUnderNode(t *testing.T) {
	verifyFail := ccMockRun(t, "if (label === 'verify:T1:1') return 'ran checks; FAIL'\n  return 'looks good; PASS'")
	for _, skipped := range []string{"verify:T1:2", "review:T1:1", "review-cross-family:T1"} {
		if slices.Contains(verifyFail.Labels, skipped) {
			t.Fatalf("stage %q must be skipped after a verify FAIL; labels=%v", skipped, verifyFail.Labels)
		}
	}
	if !slices.Contains(verifyFail.Labels, "gate:T1") {
		t.Fatalf("evidence gate must ALWAYS run; labels=%v", verifyFail.Labels)
	}
	if !strings.HasPrefix(verifyFail.GatePrompt, "Prior outcomes: ") {
		t.Fatalf("gate prompt must carry the serialized prior-outcomes ledger; got %q", verifyFail.GatePrompt)
	}
	if !strings.Contains(verifyFail.GatePrompt, `"verify_1":"FAIL"`) {
		t.Fatalf("gate prompt must report the verify FAIL; got %q", verifyFail.GatePrompt)
	}
	if !strings.Contains(verifyFail.GatePrompt, "SKIPPED:downstream-of-FAIL") {
		t.Fatalf("gate prompt must record the skipped downstream slots; got %q", verifyFail.GatePrompt)
	}

	crossReject := ccMockRun(t, "if (label === 'review-cross-family:T1') return 'BLOCKER present; REJECT'\n  return 'looks good; PASS'")
	for _, ran := range []string{"review-cross-family:T1", "gate:T1"} {
		if !slices.Contains(crossReject.Labels, ran) {
			t.Fatalf("stage %q must run when verify passes; labels=%v", ran, crossReject.Labels)
		}
	}
	if !strings.Contains(crossReject.GatePrompt, `"crossFamily":"REJECT"`) {
		t.Fatalf("gate prompt must report the cross-family REJECT; got %q", crossReject.GatePrompt)
	}
}
