package platform

import (
	"fmt"
	"path/filepath"
	"strings"
)

// omp_pipeline.go is the OMP swarm-YAML PipelineProjector (the O1 beachhead,
// full-loop-craft §2/§6). It renders a PipelineSpec into the two swarm YAMLs the
// outer omp-full-loop driver consumes: profile-driven.swarm.yaml (the inner
// per-task pipeline — profile_resolve → executor → ≤7 verify → ≤4 routine lens →
// cross-family gate → evidence gate) and reconcile.swarm.yaml (the post-barrier
// reconcile pass). The prose in each stage's `task` is the harness DRIVER LOGIC
// (it tells the agent to resolve its concrete prompt at runtime via
// `da workflow resolve-prompt`, craft §2) — not duplicated prompt content — so it
// is part of the OMP projection shape; only models, cardinality, topology, the
// workspace, and the target_count come from the spec.
//
// Output is deterministic and carries no wall-clock value: the same spec re-emits
// byte-identical YAML, and the header stamps a config digest (PipelineSpec.Digest)
// so drift from stage_profiles is visible without a re-resolve.

const (
	// OMPInnerArtifactName is the emitted inner per-task pipeline filename.
	OMPInnerArtifactName = "profile-driven.swarm.yaml"
	// OMPReconcileArtifactName is the emitted reconcile-pass filename.
	OMPReconcileArtifactName = "reconcile.swarm.yaml"

	generatedHeaderLine = "# generated by da workflow pipeline emit; do not hand-edit"
)

// ompPipelineProjector emits OMP swarm YAML from a PipelineSpec.
type ompPipelineProjector struct{}

// Platform is the OMP platform id.
func (ompPipelineProjector) Platform() string { return "omp" }

// RuntimeRelDir is the repo-relative directory the OMP swarm-YAML artifacts are
// emitted into (the same location the omp-full-loop driver reads).
func (ompPipelineProjector) RuntimeRelDir() string {
	return filepath.Join(".agents", "workflow", "runtime", "full-loop")
}

// Emit renders both OMP swarm-YAML artifacts from the spec. An app_type-agnostic
// spec (AppType == "") emits the canonical driver-consumed filenames; a
// specialized spec emits app_type-qualified filenames so it never clobbers the
// canonical skeleton the omp-full-loop driver reads.
func (p ompPipelineProjector) Emit(spec PipelineSpec) ([]PipelineArtifact, error) {
	if err := spec.Validate(); err != nil {
		return nil, err
	}
	digest := spec.Digest()
	return []PipelineArtifact{
		{Name: ompArtifactName(OMPInnerArtifactName, spec.AppType), Content: p.emitInner(spec, digest)},
		{Name: ompArtifactName(OMPReconcileArtifactName, spec.AppType), Content: p.emitReconcile(spec, digest)},
	}, nil
}

// ompArtifactName qualifies an artifact filename with the app_type when the spec
// is specialized (e.g. "profile-driven.swarm.yaml" + "docs/web" ->
// "profile-driven.docs-web.swarm.yaml"), leaving the canonical name unchanged for
// the app_type-agnostic skeleton. A "/" in an app_type is sanitized to "-".
func ompArtifactName(base, appType string) string {
	appType = strings.TrimSpace(appType)
	if appType == "" {
		return base
	}
	safe := strings.ReplaceAll(appType, "/", "-")
	suffix := ".swarm.yaml"
	stem := strings.TrimSuffix(base, suffix)
	return stem + "." + safe + suffix
}

// generatedHeader is the two-line generation stamp prepended to every emitted
// artifact: the do-not-hand-edit marker and the config digest (no wall-clock).
func generatedHeader(digest string) string {
	return fmt.Sprintf("%s\n# config-digest: %s\n", generatedHeaderLine, digest)
}

// emitInner renders profile-driven.swarm.yaml.
func (ompPipelineProjector) emitInner(spec PipelineSpec, digest string) string {
	var b strings.Builder
	b.WriteString(generatedHeader(digest))
	b.WriteString("# One task, one da workflow slot. The outer omp-full-loop driver selects work.\n")
	b.WriteString("swarm:\n")
	b.WriteString("  name: da-per-task-profile-pipeline\n")
	fmt.Fprintf(&b, "  workspace: %s\n", spec.Workspace)
	b.WriteString("  mode: pipeline\n")
	fmt.Fprintf(&b, "  target_count: %d\n", spec.TargetCount)
	fmt.Fprintf(&b, "  model: %s\n", spec.Executor.Model)
	b.WriteString("  agents:\n")

	// profile_resolve
	b.WriteString("    profile_resolve:\n")
	b.WriteString("      role: resolve task profile and explicit OMP model routes\n")
	fmt.Fprintf(&b, "      model: %s\n", spec.Executor.Model)
	b.WriteString("      task: |\n")
	b.WriteString("        Read $BUNDLE, $TASK, and the repository full-loop runtime instructions. Use the\n")
	b.WriteString("        repository-HEAD da binary. Resolve topology and lenses with `da config relevance\n")
	b.WriteString("        --task \"$TASK\" --filter topology --json` and `--filter lenses --json`. For every\n")
	b.WriteString("        verifier/lens slug call `da --json workflow resolve-prompt --kind <kind> --slug\n")
	b.WriteString("        <slug>`. Refuse a matched stage with empty model or model_family. Partition the\n")
	b.WriteString("        compatibility slug cross-harness-adversarial into cross_family_lens; all other\n")
	b.WriteString("        lenses remain routine_lenses in declared order. Require cross_family_lens.family\n")
	b.WriteString("        to differ from executor/default.family. Write $COORD/profile.json containing the\n")
	fmt.Fprintf(&b, "        task, bundle, app_type, executor route, verifier routes (max %d), routine lens routes\n", len(spec.Verifiers))
	fmt.Fprintf(&b, "        (max %d), optional cross-family route, lens_concurrency, and prior fold-back feedback.\n", len(spec.RoutineLenses))
	b.WriteString("        If cardinality exceeds those maxima or dependency/base state changed, write\n")
	b.WriteString("        $COORD/BLOCKED.md and stop. A prior $COORD/READY.md makes later iterations no-op.\n")

	// executor
	b.WriteString("\n")
	b.WriteString("    executor:\n")
	b.WriteString("      role: task implementation executor\n")
	fmt.Fprintf(&b, "      model: %s\n", spec.Executor.Model)
	b.WriteString("      waits_for: [profile_resolve]\n")
	b.WriteString("      task: |\n")
	b.WriteString("        Read $BUNDLE, $COORD/profile.json, and prior $COORD/GATE.md. Skip on BLOCKED or\n")
	fmt.Fprintf(&b, "        READY. Confirm executor model=%s and family=%s. Work only in the\n", spec.Executor.Model, spec.Executor.ModelFamily)
	b.WriteString("        delegated worktree and write_scope. Address every prior fold-back point first.\n")
	b.WriteString("        Implement, run focused tests through the production path, and commit without AI\n")
	b.WriteString("        attribution trailers. Emit $COORD/impl.md with DONE|FAIL|SKIP, commit, files,\n")
	b.WriteString("        focused evidence, and feedback addressed. Never mutate PLAN/TASKS or delegation state.\n")

	// verify slots
	emitVerifySlots(&b, spec.Verifiers)

	// routine review lens slots
	lastBeforeCross := fmt.Sprintf("verify_%d", len(spec.Verifiers))
	if len(spec.RoutineLenses) > 0 {
		emitRoutineSlots(&b, spec.RoutineLenses, len(spec.Verifiers))
		lastBeforeCross = fmt.Sprintf("review_routine_%d", len(spec.RoutineLenses))
	}

	// cross-family gate
	lastBeforeGate := lastBeforeCross
	if spec.CrossFamily != nil {
		emitCrossFamily(&b, *spec.CrossFamily, lastBeforeCross)
		lastBeforeGate = "review_cross_family"
	}

	// evidence gate
	b.WriteString("\n")
	b.WriteString("    gate:\n")
	b.WriteString("      role: task evidence and refinement artifact gate\n")
	fmt.Fprintf(&b, "      model: %s\n", spec.Executor.Model)
	fmt.Fprintf(&b, "      waits_for: [%s]\n", lastBeforeGate)
	b.WriteString("      task: |\n")
	b.WriteString("        Read profile.json plus all implementation, verifier, and review signals. On complete\n")
	b.WriteString("        evidence and approval, push/open the owner-held PR, poll the app_type delivery gate,\n")
	b.WriteString("        author a schema-valid merge-back draft, and write $COORD/READY.md. Otherwise write\n")
	b.WriteString("        $COORD/GATE.md with FOLD-BACK and every actionable blocker for the next bounded\n")
	b.WriteString("        iteration. Write $COORD/refinement.json with idempotent stable slugs for task_notes,\n")
	b.WriteString("        plan_summary observations, and cross-cutting proposal candidates. Never merge, advance,\n")
	b.WriteString("        close out a delegation, or mutate canonical plan/task state. Commit only coordination\n")
	b.WriteString("        artifacts through the configured CAS state channel.\n")

	return b.String()
}

// emitVerifySlots renders the contiguous verify_1..N slot group. verify_1 defines
// the &verify_slot anchor; later slots merge it and override the model only when
// their route differs, so a uniform-model pipeline emits no redundant model line.
func emitVerifySlots(b *strings.Builder, verifiers []StageRoute) {
	b.WriteString("\n")
	anchorModel := verifiers[0].Model
	for i, route := range verifiers {
		n := i + 1
		if i == 0 {
			fmt.Fprintf(b, "    verify_1: &verify_slot\n")
			b.WriteString("      role: verifier slot 1\n")
			fmt.Fprintf(b, "      model: %s\n", route.Model)
			b.WriteString("      waits_for: [executor]\n")
			b.WriteString("      task: |\n")
			b.WriteString("        Read $COORD/profile.json and impl.md. Run verifier_routes[0] if present, using its\n")
			b.WriteString("        resolved prompt composition; require its route to equal this agent's explicit model\n")
			fmt.Fprintf(b, "        and family=%s. Emit $COORD/verify-1.md PASS|FAIL|SKIP with command and evidence.\n", route.ModelFamily)
			b.WriteString("        Never mutate canonical workflow state.\n")
			continue
		}
		fmt.Fprintf(b, "    verify_%d:\n", n)
		b.WriteString("      <<: *verify_slot\n")
		fmt.Fprintf(b, "      role: verifier slot %d\n", n)
		if route.Model != anchorModel {
			fmt.Fprintf(b, "      model: %s\n", route.Model)
		}
		fmt.Fprintf(b, "      waits_for: [verify_%d]\n", n-1)
		if n == 2 {
			b.WriteString("      task: \"Run verifier_routes[1] under the same contract; gate on verify-1 PASS; emit $COORD/verify-2.md.\"\n")
		} else {
			fmt.Fprintf(b, "      task: \"Run verifier_routes[%d] under the same contract; gate on prior PASS; emit $COORD/verify-%d.md.\"\n", n-1, n)
		}
	}
}

// emitRoutineSlots renders the contiguous review_routine_1..M slot group.
// review_routine_1 defines the &routine_review anchor and waits on the last
// verify slot; later slots chain and override the model only when their route
// differs.
func emitRoutineSlots(b *strings.Builder, lenses []StageRoute, numVerifiers int) {
	b.WriteString("\n")
	anchorModel := lenses[0].Model
	for i, route := range lenses {
		n := i + 1
		if i == 0 {
			b.WriteString("    review_routine_1: &routine_review\n")
			b.WriteString("      role: routine review lens slot 1\n")
			fmt.Fprintf(b, "      model: %s\n", route.Model)
			fmt.Fprintf(b, "      waits_for: [verify_%d]\n", numVerifiers)
			b.WriteString("      task: |\n")
			b.WriteString("        Read profile.json, implementation, and verifier evidence. Run routine_lenses[0] if\n")
			b.WriteString("        present and all verifiers passed. Require its route to equal this agent's explicit\n")
			fmt.Fprintf(b, "        model and family=%s. Review read-only and emit $COORD/review-routine-1.md\n", route.ModelFamily)
			b.WriteString("        APPROVE|REJECT|SKIP with cited findings. Never mutate canonical workflow state.\n")
			continue
		}
		fmt.Fprintf(b, "    review_routine_%d:\n", n)
		b.WriteString("      <<: *routine_review\n")
		fmt.Fprintf(b, "      role: routine review lens slot %d\n", n)
		if route.Model != anchorModel {
			fmt.Fprintf(b, "      model: %s\n", route.Model)
		}
		fmt.Fprintf(b, "      waits_for: [review_routine_%d]\n", n-1)
		fmt.Fprintf(b, "      task: \"Run routine_lenses[%d]; honor lens_concurrency and prior rejection; emit $COORD/review-routine-%d.md.\"\n", n-1, n)
	}
}

// emitCrossFamily renders the blocking cross-model-family adversarial review
// stage. It binds to the NAMED cross-harness-adversarial slug and asserts family
// inequality against the executor (craft §2 RULE-7), never a numeric slot index.
func emitCrossFamily(b *strings.Builder, route StageRoute, waitsFor string) {
	b.WriteString("\n")
	b.WriteString("    review_cross_family:\n")
	b.WriteString("      role: blocking cross-model-family adversarial reviewer through OMP\n")
	fmt.Fprintf(b, "      model: %s\n", route.Model)
	fmt.Fprintf(b, "      waits_for: [%s]\n", waitsFor)
	b.WriteString("      task: |\n")
	b.WriteString("        Read profile.json and all evidence. If no cross_family_lens is configured, emit SKIP.\n")
	fmt.Fprintf(b, "        Otherwise require slug=%s, model=%s, family=%s, and\n", route.Slug, route.Model, route.ModelFamily)
	b.WriteString("        family different from executor/default. Run its resolved prompt read-only through OMP.\n")
	b.WriteString("        Mutation-check tests and inspect production-path wiring. Emit\n")
	b.WriteString("        $COORD/review-cross-family.md APPROVE|REJECT|SKIP with cited findings. Any\n")
	b.WriteString("        BLOCKER/HIGH rejects. Do not invoke the Codex CLI or apply Codex sandbox/permission flags.\n")
}

// emitReconcile renders reconcile.swarm.yaml. The reconcile stage is
// app_type-agnostic lifecycle logic, so only the workspace and the model (the
// executor route) come from the spec; the prose is fixed driver logic.
func (ompPipelineProjector) emitReconcile(spec PipelineSpec, digest string) string {
	var b strings.Builder
	b.WriteString(generatedHeader(digest))
	b.WriteString("# One reconciliation pass after an outer-loop wave barrier.\n")
	b.WriteString("swarm:\n")
	b.WriteString("  name: da-full-loop-wave-reconcile\n")
	fmt.Fprintf(&b, "  workspace: %s\n", spec.Workspace)
	b.WriteString("  mode: sequential\n")
	b.WriteString("  target_count: 1\n")
	fmt.Fprintf(&b, "  model: %s\n", spec.Executor.Model)
	b.WriteString("  agents:\n")
	b.WriteString("    reconcile:\n")
	b.WriteString("      role: serialized da lifecycle and meta-loop reconciler\n")
	fmt.Fprintf(&b, "      model: %s\n", spec.Executor.Model)
	b.WriteString("      task: |\n")
	b.WriteString("        Read $WAVE_MANIFEST and process its task results in manifest order, one at a time.\n")
	b.WriteString("        Use the repository-HEAD da binary for every workflow mutation. Re-read the task,\n")
	b.WriteString("        delegation, PR, slots, and eligible state before each mutation; never edit PLAN.yaml or\n")
	b.WriteString("        TASKS.yaml directly.\n")
	b.WriteString("\n")
	b.WriteString("        READY result:\n")
	b.WriteString("        - Validate merge-back frontmatter and evidence; perform delegation gate readback.\n")
	b.WriteString("        - Leave the PR owner-held. If owner outcome is not present, preserve\n")
	b.WriteString("          awaiting_owner_review and continue; do not consume a slot.\n")
	b.WriteString("        - If an owner merge/reject is present, run the corresponding da delegation closeout and\n")
	b.WriteString("          checkpoint/advance sequence exactly once.\n")
	b.WriteString("\n")
	b.WriteString("        FOLD-BACK result:\n")
	b.WriteString("        - This is the terminal result after the inner pipeline exhausted its bounded target_count;\n")
	b.WriteString("          retryable lens/verifier rejection already re-entered the executor inside that one active\n")
	b.WriteString("          delegation. Do not fan the task out again while its delegation is active.\n")
	b.WriteString("        - For each task-scoped item run `da workflow fold-back create --plan <P> --task <T>\n")
	b.WriteString("          --observation <text> --slug <stable>`; refine existing slugs with fold-back update.\n")
	b.WriteString("          Plan-scoped items omit --task. Confirm routed_to through fold-back list.\n")
	b.WriteString("        - Persist a failed merge-back/readback artifact as required, evaluate the delegation gate,\n")
	b.WriteString("          then close out with decision=reject and the fold-back evidence. The canonical task becomes\n")
	b.WriteString("          blocked and its slot is freed. A later explicit unblock/replan creates a fresh delegation.\n")
	b.WriteString("\n")
	b.WriteString("        FAILED/UNKNOWN/BLOCKED result:\n")
	b.WriteString("        - Treat a non-zero or missing inner exit as a recoverable lifecycle failure, never as a\n")
	b.WriteString("          reason to abandon the already-created delegation. Record an idempotent task fold-back\n")
	b.WriteString("          containing the exit/result and available logs.\n")
	b.WriteString("        - Persist the required failed merge-back/readback artifact, evaluate the parent gate, and\n")
	b.WriteString("          close out decision=reject so the task becomes blocked and the occupied slot is freed.\n")
	b.WriteString("          A recovered crash with no terminal artifact follows this same path. Never claim success\n")
	b.WriteString("          or leave an orphaned in_progress delegation.\n")
	b.WriteString("\n")
	b.WriteString("        REFINEMENT candidates:\n")
	b.WriteString("        - First/local occurrence stays a task_note or plan_summary.\n")
	b.WriteString("        - Confirmed recurring/cross-cutting candidates run fold-back create --propose with a stable\n")
	b.WriteString("          slug. Shared preference changes use prefs set-shared and remain human-gated by da review.\n")
	b.WriteString("        - Never approve a proposal during the run that produced it.\n")
	b.WriteString("\n")
	b.WriteString("        Record verification/checkpoint/hook outcomes and recompute the iteration score when the\n")
	b.WriteString("        lifecycle preconditions are satisfied. Preserve the iteration-close archived-mergeback\n")
	b.WriteString("        sentinel workaround. After every canonical write, re-run `da --json workflow slots` and\n")
	b.WriteString("        `da --json workflow eligible`; append the observed transition to $WAVE_DIR/reconcile.md.\n")
	b.WriteString("        Emit $WAVE_DIR/RECONCILED only after every result has either transitioned or has an explicit\n")
	b.WriteString("        owner/external wait reason. Any ambiguous state blocks the next wave.\n")
	return b.String()
}
