// Code generated by `pnpm types` (json-schema-to-typescript). DO NOT EDIT.
// Re-generate with: pnpm --filter r2-observability-dashboard types
// Sources: schemas/dashboard-{run,iteration,rubric,event}.schema.json

/**
 * Presentation projection of a single agent-run session for the R2 observability dashboard. A 'run' is one session_id's worth of iterations discovered in a resolved iter-log root. RunSummary is the row shape returned by GET /api/runs; RunDetail (the full object) is returned by GET /api/runs/{session_id}. Sourced from internal/scoring.SessionScore plus iter-log walk over internal/scoring.IterationRecord. v1 is read-only; R5 augments this payload behind a composition point (e.g. a labels[] array) without forking the shape — so additionalProperties is false here to catch drift, and additive evolution happens via explicit new optional fields.
 */
export interface R2DashboardRunSessionDTO {
  /**
   * Stable session identifier (IterationRecord.Agent.SessionID). The addressable key for GET /api/runs/{session_id} and the session-<id>.score.yaml sidecar.
   */
  session_id: string
  /**
   * Agent platform harness for the session (claude-code, codex, cursor). Taken from the most recent iteration's AgentInfo.Harness; empty when no iteration carried agent identity.
   */
  harness?: string
  /**
   * Model id for the session (AgentInfo.Model); empty when unknown.
   */
  model?: string
  /**
   * Plan id active at the session's last iteration (IterationRecord.Wave); empty when unknown.
   */
  wave?: string
  /**
   * Rubric version the session aggregate was scored under (SessionScore.RubricVersion). May differ from the active rubric reported by /api/rubric; the UI renders a mismatch pill (spec D3).
   */
  rubric_version: string
  /**
   * Number of iterations belonging to this session (len(SessionScore.Iterations)). 0 is valid for a session present in the log with no scorable iterations.
   */
  iteration_count: number
  /**
   * False when no iteration in the session has a numeric score (SessionScore.Scored). When false, `score` is null and `band` is 'unscored'.
   */
  scored: boolean
  /**
   * Mean of the scored per-iteration values (SessionScore.Value). null when scored is false. Never an error — missing scores degrade to null per spec R2.
   */
  score: number | null
  /**
   * Human-readable band for `score` (SessionScore.Band), or 'unscored' when scored is false.
   */
  band: 'excellent' | 'good' | 'fair' | 'poor' | 'unscored'
  /**
   * Lowest iteration number in the session; null when iteration_count is 0.
   */
  first_iteration?: number | null
  /**
   * Highest iteration number in the session; null when iteration_count is 0.
   */
  last_iteration?: number | null
  /**
   * RFC3339 UTC mtime of the newest contributing iter-log or score sidecar file for the session. Drives the runs-grid 'last update' column and is the basis for the response ETag. null when no file mtime is resolvable.
   */
  last_update?: string | null
  /**
   * Resolved iter-log root this session was discovered in (per design.md Q5 root list). Lets the client pass ?iter_log_dir= back on drill-down endpoints for non-active roots.
   */
  iter_log_dir?: string
  /**
   * Lightweight per-iteration score refs (SessionScore.PerIteration) so the runs grid can sparkline a session without fetching every iteration sidecar. Present in RunDetail; omitted from RunSummary rows to keep the list payload small.
   */
  per_iteration?: {
    iteration: number
    scored: boolean
    score: number | null
    band: 'excellent' | 'good' | 'fair' | 'poor' | 'unscored'
  }[]
  /**
   * Mean of per-iteration session_tokens.cache_hit_rate across iterations that captured token telemetry; null when none did. Feeds the aggregate cache-trend view.
   */
  mean_cache_hit_rate?: number | null
}

/**
 * Presentation projection of a single agent-run iteration for the R2 observability dashboard. IterationSummary is the row shape inside GET /api/runs/{session_id}/iterations; IterationDetail (the full object, with breakdown + integrity + objective) is returned by GET /api/iterations/{n}. Sourced from internal/scoring.IterationRecord plus the iter-N.score.yaml sidecar (internal/scoring.PersistedScore). A listed iteration with no sidecar yet returns score: null / scored: false (spec R2) — never an error.
 */
export interface R2DashboardIterationDTO {
  /**
   * Iteration number (IterationRecord.Iteration / PersistedScore.Iteration). Addressable key for GET /api/iterations/{n}.
   */
  iteration: number
  /**
   * Session this iteration belongs to (IterationRecord.Agent.SessionID); empty for pre-v2 (flat) entries that never carried agent identity.
   */
  session_id?: string
  /**
   * Iteration-log schema version the record was normalized from (IterationRecord.SchemaVersion).
   */
  schema_version?: 1 | 2
  /**
   * Checkpoint date as recorded in the iter-log (IterationRecord.Date, YYYY-MM-DD); empty when absent.
   */
  date?: string
  /**
   * Plan id active at checkpoint time (IterationRecord.Wave).
   */
  wave?: string
  /**
   * Task id for the iteration (IterationRecord.TaskID).
   */
  task_id?: string
  /**
   * Git commit SHA at checkpoint time (IterationRecord.Commit); empty when none.
   */
  commit?: string
  /**
   * Rubric version the score was computed under (PersistedScore.RubricVersion). Empty string when the iteration is unscored and no sidecar exists yet.
   */
  rubric_version: string
  /**
   * False when no rubric signal was present (PersistedScore.Scored) OR when the score sidecar has not been written yet (staleness window, spec R2 / OQ2). The UI renders a 'scoring…' pill for the latter.
   */
  scored: boolean
  /**
   * Numeric score in [0,1] (PersistedScore.Value); null when scored is false.
   */
  score: number | null
  /**
   * Human-readable band for `score` (PersistedScore.Band), or 'unscored'.
   */
  band: 'excellent' | 'good' | 'fair' | 'poor' | 'unscored'
  /**
   * IterationRecord.FilesChanged.
   */
  files_changed?: number
  /**
   * IterationRecord.LinesAdded.
   */
  lines_added?: number
  /**
   * IterationRecord.LinesRemoved.
   */
  lines_removed?: number
  /**
   * Implementation-role retries (IterationRecord.Impl.Retries).
   */
  retries?: number
  /**
   * Number of comparable integrity observations (claimed AND observed present) for this iteration. Drives the integrity badge on the iteration row without sending the full observation list. Present on both summary and detail.
   */
  integrity_observation_count?: number
  /**
   * Assistant turns scanned for the iteration (session_tokens.message_count when captured); null when unavailable. Spec R3.
   */
  transcript_turn_count?: number | null
  /**
   * Per-iteration token telemetry (IterationRecord.SessionTokens / TokenUsage); null when the entry never captured token telemetry.
   */
  token_usage?: {
    input_tokens?: number
    output_tokens?: number
    cache_read_tokens?: number
    cache_creation_tokens?: number
    cache_hit_rate?: number
  } | null
  /**
   * Per-verifier outcomes (IterationRecord.Verifiers). Present in IterationDetail only.
   */
  verifiers?: {
    type: string
    status: 'pass' | 'fail' | 'partial' | 'unknown'
    gate_passed?: boolean
    tests_added?: number
    retries?: number
  }[]
  /**
   * Per-signal score breakdown, one row per rubric signal in rubric order (PersistedScore.Breakdown / PersistedContribution). Present in IterationDetail only. Empty array when the iteration is unscored.
   */
  breakdown?: {
    /**
     * Rubric signal id (PersistedContribution.Signal).
     */
    signal:
      | 'landed'
      | 'verifier'
      | 'tests'
      | 'human_label'
      | 'correction_pressure'
      | 'scope'
      | 'hook_outcomes'
      | 'token_efficiency'
    label: string
    /**
     * False when the telemetry to compute the signal was absent; an absent signal contributes 0 (effective_weight 0).
     */
    present: boolean
    /**
     * Signal sub-score in [0,1]; meaningful only when present.
     */
    sub_score: number
    /**
     * Short human-readable note explaining the sub-score (PersistedContribution.Detail).
     */
    detail?: string
    /**
     * Signal's declared rubric weight before renormalization.
     */
    nominal_weight: number
    /**
     * Weight after renormalizing over present signals; 0 when absent.
     */
    effective_weight: number
    /**
     * effective_weight * sub_score; present-signal contributions sum to `score`.
     */
    contribution: number
  }[]
  /**
   * Claimed-vs-observed integrity observations for two-way signals (internal/scoring.IntegrityObservation). Never affects the numeric score. Present in IterationDetail only.
   */
  integrity?: {
    /**
     * The two-way signal observed (IntegrityObservation.Signal).
     */
    signal: 'landed' | 'verifier' | 'tests' | 'scope'
    /**
     * Role that made the self-reported claim (IntegrityObservation.Role).
     */
    role: 'impl' | 'verifier' | 'review'
    claimed: SignalSide
    observed: SignalSide1
    /**
     * True when both claimed and observed are present (IntegrityObservation.Comparable); only then is `delta` meaningful.
     */
    comparable: boolean
    /**
     * observed.sub_score - claimed.sub_score when comparable; negative is an over-claim. null when not comparable.
     */
    delta?: number | null
  }[]
  /**
   * Transcript-derived objective process checks (internal/scoring.IterationObjectives) — facts with no self-reported counterpart. Present in IterationDetail; null when no transcript was scanned.
   */
  objective?: {
    ran_cli_command?: SignalSide2
    committed_after_tests?: SignalSide2
    read_loop_state?: SignalSide2
  } | null
}
/**
 * Self-reported side (IntegrityObservation.Claimed).
 */
export interface SignalSide {
  present: boolean
  sub_score?: number
  detail?: string
}
/**
 * Objective side (IntegrityObservation.Observed).
 */
export interface SignalSide1 {
  present: boolean
  sub_score?: number
  detail?: string
}
/**
 * Mirror of internal/scoring.SignalValue: present + sub_score + detail. sub_score is meaningful only when present.
 */
export interface SignalSide2 {
  present: boolean
  sub_score?: number
  detail?: string
}

/**
 * Presentation projection of the active outcome-scoring rubric for the R2 dashboard rubric-explainer view. Returned by GET /api/rubric. Sourced from internal/scoring.DefaultRubric() at process start (spec R4): version, combination method, the signal set with weights + labels + descriptions, and the band ladder. Read-only; the rubric is versioned (spec D3) so every iteration/run DTO carries the rubric_version it was scored under and the UI flags a mismatch against this active version.
 */
export interface R2DashboardRubricDTO {
  /**
   * Active rubric semantic version (Rubric.Version / scoring.RubricVersion, e.g. '2.1.0').
   */
  version: string
  /**
   * How per-signal sub-scores combine (Rubric.Combination / CombinationMethod). v1 only ships weighted_mean_renormalized.
   */
  combination: 'weighted_mean_renormalized'
  /**
   * The rubric's signals in declared order (Rubric.Signals / SignalSpec). Weights sum to 1.0.
   *
   * @minItems 1
   */
  signals: [
    {
      /**
       * Signal id (SignalSpec.ID).
       */
      id:
        | 'landed'
        | 'verifier'
        | 'tests'
        | 'human_label'
        | 'correction_pressure'
        | 'scope'
        | 'hook_outcomes'
        | 'token_efficiency'
      /**
       * Human-readable label (SignalSpec.Label).
       */
      label: string
      /**
       * Nominal weight in the combination (SignalSpec.Weight).
       */
      weight: number
      /**
       * One-line description of what the signal measures (SignalSpec.Description).
       */
      description: string
      /**
       * True when the signal has both an objective and a self-reported source and therefore emits an integrity observation (SignalSpec.TwoWay).
       */
      two_way: boolean
    },
    ...{
      /**
       * Signal id (SignalSpec.ID).
       */
      id:
        | 'landed'
        | 'verifier'
        | 'tests'
        | 'human_label'
        | 'correction_pressure'
        | 'scope'
        | 'hook_outcomes'
        | 'token_efficiency'
      /**
       * Human-readable label (SignalSpec.Label).
       */
      label: string
      /**
       * Nominal weight in the combination (SignalSpec.Weight).
       */
      weight: number
      /**
       * One-line description of what the signal measures (SignalSpec.Description).
       */
      description: string
      /**
       * True when the signal has both an objective and a self-reported source and therefore emits an integrity observation (SignalSpec.TwoWay).
       */
      two_way: boolean
    }[]
  ]
  /**
   * Score-band ladder sorted descending by min (Rubric.Bands / ScoreBand). The lowest band is anchored at min 0 so every score in [0,1] lands. The 'unscored' band is implicit (no numeric range) and is NOT listed here; DTOs report band 'unscored' when scored is false.
   *
   * @minItems 1
   */
  bands: [
    {
      /**
       * Band name (ScoreBand.Name).
       */
      name: 'excellent' | 'good' | 'fair' | 'poor'
      /**
       * Inclusive lower bound for the band (ScoreBand.Min).
       */
      min: number
    },
    ...{
      /**
       * Band name (ScoreBand.Name).
       */
      name: 'excellent' | 'good' | 'fair' | 'poor'
      /**
       * Inclusive lower bound for the band (ScoreBand.Min).
       */
      min: number
    }[]
  ]
}

/**
 * Shape of one event delivered over the Server-Sent Events channel at GET /api/stream (design.md Q3: SSE chosen over WebSocket because traffic is server->client only). This schema validates the JSON carried in the SSE frame's `data:` field. The SSE frame itself adds transport metadata: `event: <type>` (the topic, mirrored in `type` below), `id: <seq>` (monotonic per-connection sequence), and for heartbeats a bare `: ping` comment line. v1 has NO server-side replay of missed events (spec D2.2 fallback): on reconnect the client refetches affected queries. So `seq` is per-connection and resets on reconnect — it is for client-side ordering/dedupe within a single connection, not durable cursoring.
 */
export interface R2DashboardSSEEventDTO {
  /**
   * Event topic, mirrored in the SSE `event:` field. iteration.scored: a new iter-N.score.yaml sidecar appeared (spec R5). session.updated: a session-<id>.score.yaml was rewritten under the same rubric version (spec R6). score.recomputed: an existing iteration score changed in place. rubric.changed: the rubric was recomputed under a NEW version — a broadcast that triggers a full client reload (spec R7). heartbeat: 15s keepalive to defeat proxy idle-timeouts (usually sent as a `: ping` comment, but also valid as a typed event).
   */
  type: 'iteration.scored' | 'session.updated' | 'score.recomputed' | 'rubric.changed' | 'heartbeat'
  /**
   * Monotonic per-connection sequence number, mirrored in the SSE `id:` field. Resets to 0 on a new connection (no durable replay in v1).
   */
  seq: number
  /**
   * RFC3339 UTC time the event was published.
   */
  ts?: string
  /**
   * Event-type-specific body. Keyed identifiers (session_id, iteration) let the client invalidate exactly the affected TanStack Query keys. The payload is intentionally a thin key set, NOT the full DTO — the client refetches the affected resource on receipt.
   */
  payload:
    | {
        session_id: string
        iteration: number
        /**
         * New band for the iteration, so the UI can tint a live tick without an immediate refetch.
         */
        band?: 'excellent' | 'good' | 'fair' | 'poor' | 'unscored'
      }
    | {
        session_id: string
      }
    | {
        rubric_version: string
      }
    | {}
}
