/**
 * Generates src/api/types.gen.ts from the four dashboard JSON Schemas.
 * Run via: pnpm types
 *
 * Source schemas live at <repo-root>/schemas/dashboard-*.schema.json.
 * This script resolves them relative to the repo root (three levels up from
 * web/dashboard/scripts/).
 */

import { compileFromFile } from 'json-schema-to-typescript'
import { writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const schemasDir = resolve(__dirname, '../../../schemas')
const outFile = resolve(__dirname, '../src/api/types.gen.ts')

const schemas = [
  'dashboard-run.schema.json',
  'dashboard-iteration.schema.json',
  'dashboard-rubric.schema.json',
  'dashboard-event.schema.json',
]

const header = [
  '// Code generated by `pnpm types` (json-schema-to-typescript). DO NOT EDIT.',
  '// Re-generate with: pnpm --filter r2-observability-dashboard types',
  '// Sources: schemas/dashboard-{run,iteration,rubric,event}.schema.json',
  '',
  '',
].join('\n')

const parts = await Promise.all(
  schemas.map((s) =>
    compileFromFile(resolve(schemasDir, s), {
      bannerComment: '',
      style: { singleQuote: true, semi: false },
    }),
  ),
)

writeFileSync(outFile, header + parts.join('\n'), 'utf-8')
console.log(`types.gen.ts written (${schemas.length} schemas → ${outFile})`)
