package projection

import (
	"reflect"
	"sort"
	"strings"

	yaml "go.yaml.in/yaml/v3"
)

// Fidelity is the graded result of an ingest->regenerate round-trip for one
// file. The grades are ordered: ByteIdentical is the strongest (zero git
// churn), SemanticEqual means the parsed structure matches but the bytes differ
// (cosmetic reflow — a one-time churn on first regeneration, clean thereafter),
// and Lossy means data the schema can't hold was dropped.
type Fidelity struct {
	Path          string
	Grade         Grade
	OrigBytes     int
	RegenBytes    int
	Reasons       []string // human-readable causes of any byte difference
	DroppedKeys   []string // non-schema top-level keys lost (Plan only)
	DroppedFields []string // schema fields that round-trip lost a value
}

// Grade is the round-trip fidelity tier.
type Grade string

const (
	// ByteIdentical: regenerated bytes equal the original byte-for-byte.
	ByteIdentical Grade = "byte-identical"
	// SemanticEqual: parsed structures match but bytes differ (cosmetic).
	SemanticEqual Grade = "semantic-equal"
	// Normalized: the regen differs only by materializing a schema field that
	// was ABSENT in the file to its zero value (e.g. a task with no `blocks:`
	// key gains `blocks: []`). No information is lost — the typed model and the
	// regenerated file agree — but the original chose to omit the key. This is
	// a one-time normalization, churn-free thereafter. It is NOT data loss.
	Normalized Grade = "normalized"
	// Lossy: a value the canonical schema cannot represent was dropped
	// (non-schema top-level keys, or comments-as-data). True information loss.
	Lossy Grade = "lossy"
)

// GradePlanRoundTrip ingests, regenerates, and grades a PLAN.yaml's bytes.
func GradePlanRoundTrip(path string, orig []byte) (Fidelity, error) {
	p, err := ParsePlan(orig)
	if err != nil {
		return Fidelity{}, err
	}
	regen, err := SerializePlan(p)
	if err != nil {
		return Fidelity{}, err
	}
	// modelEqual: re-ingesting the regen yields a typed model equal to the
	// original's. The typed model canonicalizes absent keys to zero values, so
	// this is true when the only difference is field materialization.
	p2, _ := ParsePlan(regen)
	modelEqual := plansModelEqual(p, p2)
	f := gradeBytes(path, orig, regen, modelEqual)
	for k := range p.ExtraKeys {
		f.DroppedKeys = append(f.DroppedKeys, k)
	}
	if len(f.DroppedKeys) > 0 {
		sort.Strings(f.DroppedKeys)
		f.Grade = Lossy
		// Replace any cosmetic/normalized reason: the dropped non-schema keys are
		// the dominant finding for this file.
		f.Reasons = []string{"dropped non-schema top-level key(s): " + strings.Join(f.DroppedKeys, ", ")}
	}
	return f, nil
}

// plansModelEqual compares two parsed plans ignoring ExtraKeys (those are
// reported separately as the lossy residue).
func plansModelEqual(a, b *Plan) bool {
	if a == nil || b == nil {
		return a == b
	}
	ax, bx := a.ExtraKeys, b.ExtraKeys
	a.ExtraKeys, b.ExtraKeys = nil, nil
	eq := reflect.DeepEqual(a, b)
	a.ExtraKeys, b.ExtraKeys = ax, bx
	return eq
}

// GradeTasksRoundTrip ingests, regenerates, and grades a TASKS.yaml's bytes.
func GradeTasksRoundTrip(path string, orig []byte) (Fidelity, error) {
	tf, err := ParseTasks(orig)
	if err != nil {
		return Fidelity{}, err
	}
	regen, err := SerializeTasks(tf)
	if err != nil {
		return Fidelity{}, err
	}
	tf2, _ := ParseTasks(regen)
	modelEqual := tasksModelEqual(tf, tf2)
	return gradeBytes(path, orig, regen, modelEqual), nil
}

// tasksModelEqual compares two task files treating nil and empty slices as
// equal — a task that OMITS `blocks:` (nil slice) and one that writes
// `blocks: []` (empty slice) carry the same information. reflect.DeepEqual
// alone would call them different, mislabeling pure field materialization as
// loss.
func tasksModelEqual(a, b *TaskFile) bool {
	if a == nil || b == nil {
		return a == b
	}
	if a.SchemaVersion != b.SchemaVersion || a.PlanID != b.PlanID || len(a.Tasks) != len(b.Tasks) {
		return false
	}
	for i := range a.Tasks {
		if !taskEqual(a.Tasks[i], b.Tasks[i]) {
			return false
		}
	}
	return true
}

func taskEqual(a, b Task) bool {
	return a.ID == b.ID && a.Title == b.Title && a.Status == b.Status &&
		a.Owner == b.Owner && a.VerificationRequired == b.VerificationRequired &&
		a.Notes == b.Notes && a.AppType == b.AppType &&
		sliceEqual(a.DependsOn, b.DependsOn) && sliceEqual(a.Blocks, b.Blocks) &&
		sliceEqual(a.WriteScope, b.WriteScope)
}

// sliceEqual treats nil and empty as equal, then compares elementwise.
func sliceEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// gradeBytes classifies orig vs regen. modelEqual reports whether the two
// decode to the SAME typed model (absent keys canonicalized to zero values).
//   - byte-equal                 -> ByteIdentical
//   - generic-YAML-equal         -> SemanticEqual (pure cosmetic reflow)
//   - model-equal but not above  -> Normalized (absent schema key materialized)
//   - else                       -> Lossy (true data loss)
func gradeBytes(path string, orig, regen []byte, modelEqual bool) Fidelity {
	f := Fidelity{Path: path, OrigBytes: len(orig), RegenBytes: len(regen)}
	if string(orig) == string(regen) {
		f.Grade = ByteIdentical
		return f
	}
	if semanticEqualYAML(orig, regen) {
		f.Grade = SemanticEqual
		f.Reasons = diffReasons(orig, regen)
		return f
	}
	added, removed := keySetDelta(orig, regen)
	if modelEqual {
		f.Grade = Normalized
		msg := "regen materializes absent schema key(s) to zero value"
		if len(added) > 0 {
			msg += ": " + strings.Join(added, ", ")
		}
		f.Reasons = append(f.Reasons, msg)
		f.DroppedFields = added
		return f
	}
	f.Grade = Lossy
	if len(removed) > 0 {
		f.Reasons = append(f.Reasons, "round-trip dropped key(s): "+strings.Join(removed, ", "))
	} else {
		f.Reasons = append(f.Reasons, "re-parsed structures differ: round-trip lost or altered data")
	}
	return f
}

// keySetDelta returns the union of mapping keys (recursively, by key name) that
// appear in regen-but-not-orig (added) and orig-but-not-regen (removed). It is
// used to distinguish field materialization (added only) from true loss
// (any removed). Keys are name-only (not path-qualified) which is sufficient to
// classify the round-trip outcome on these files.
func keySetDelta(orig, regen []byte) (added, removed []string) {
	var vo, vr any
	if yaml.Unmarshal(orig, &vo) != nil || yaml.Unmarshal(regen, &vr) != nil {
		return nil, nil
	}
	ko, kr := map[string]bool{}, map[string]bool{}
	collectKeys(vo, ko)
	collectKeys(vr, kr)
	for k := range kr {
		if !ko[k] {
			added = append(added, k)
		}
	}
	for k := range ko {
		if !kr[k] {
			removed = append(removed, k)
		}
	}
	return added, removed
}

// collectKeys walks a decoded YAML value and records every mapping key name.
func collectKeys(v any, into map[string]bool) {
	switch t := v.(type) {
	case map[string]any:
		for k, val := range t {
			into[k] = true
			collectKeys(val, into)
		}
	case []any:
		for _, e := range t {
			collectKeys(e, into)
		}
	}
}

// semanticEqualYAML reports whether two YAML byte streams decode to the same
// generic structure (maps/slices/scalars). This is the precise definition of
// "lossless even if not byte-identical": same information, different layout.
func semanticEqualYAML(a, b []byte) bool {
	var va, vb any
	if err := yaml.Unmarshal(a, &va); err != nil {
		return false
	}
	if err := yaml.Unmarshal(b, &vb); err != nil {
		return false
	}
	return reflect.DeepEqual(va, vb)
}

// diffReasons returns the cosmetic causes that make two semantically-equal YAML
// streams differ byte-wise. These are exactly the serialization rules the spec
// must pin so regeneration is churn-free against da-written files.
func diffReasons(orig, regen []byte) []string {
	var reasons []string
	if hasComments(orig) {
		reasons = append(reasons, "original carries YAML comments (# ...) which the canonical projection drops")
	}
	if hasBlankSeparatorLines(orig) && !hasBlankSeparatorLines(regen) {
		reasons = append(reasons, "original has cosmetic blank separator lines between items")
	}
	if blockSeqIndent(orig) != blockSeqIndent(regen) {
		reasons = append(reasons, "block-sequence indent differs (file uses non-canonical indent; canonical = 4 spaces)")
	}
	if quoteStyleDiffers(orig, regen) {
		reasons = append(reasons, "scalar quoting/block-scalar style differs (e.g. forced single-quotes vs plain, or |- body indent)")
	}
	if len(reasons) == 0 {
		reasons = append(reasons, "whitespace/style reflow (semantically identical)")
	}
	return reasons
}

// hasComments reports whether the byte stream contains a YAML comment line.
func hasComments(b []byte) bool {
	for _, line := range strings.Split(string(b), "\n") {
		t := strings.TrimSpace(line)
		if strings.HasPrefix(t, "#") {
			return true
		}
	}
	return false
}

// hasBlankSeparatorLines reports whether there is an empty line between content.
func hasBlankSeparatorLines(b []byte) bool {
	lines := strings.Split(string(b), "\n")
	for i := 1; i < len(lines)-1; i++ {
		if strings.TrimSpace(lines[i]) == "" {
			return true
		}
	}
	return false
}

// blockSeqIndent returns the leading-space count of the first block-sequence
// entry ("- ") under the tasks: key, a proxy for the file's indent style.
func blockSeqIndent(b []byte) int {
	for _, line := range strings.Split(string(b), "\n") {
		trimmed := strings.TrimLeft(line, " ")
		if strings.HasPrefix(trimmed, "- ") {
			return len(line) - len(trimmed)
		}
	}
	return -1
}

// quoteStyleDiffers reports whether the count of single-quoted scalar lines
// differs between the two streams (a cheap proxy for forced-quote vs plain).
func quoteStyleDiffers(orig, regen []byte) bool {
	return countQuoted(orig) != countQuoted(regen) || countBlockScalars(orig) != countBlockScalars(regen)
}

func countQuoted(b []byte) int {
	n := 0
	for _, line := range strings.Split(string(b), "\n") {
		if strings.Contains(line, ": '") || strings.Contains(line, ": \"") {
			n++
		}
	}
	return n
}

func countBlockScalars(b []byte) int {
	n := 0
	for _, line := range strings.Split(string(b), "\n") {
		t := strings.TrimRight(line, " ")
		if strings.HasSuffix(t, ": |-") || strings.HasSuffix(t, ": |") || strings.HasSuffix(t, ": >-") {
			n++
		}
	}
	return n
}
