package workflow

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/AGOrcha/dot-agents/internal/config"
	"github.com/AGOrcha/dot-agents/internal/platform"
)

type failingPipelineProjector struct{}

func (failingPipelineProjector) Platform() string { return "test" }

func (failingPipelineProjector) RuntimeRelDir() string { return ".test" }

func (failingPipelineProjector) Emit(platform.PipelineSpec) ([]platform.PipelineArtifact, error) {
	return nil, errors.New("projector emit failed")
}

func pipelineFixtureSnapshot() *config.Snapshot {
	claude := config.StageProfile{Model: "claude-opus-4-8", ModelFamily: "claude"}
	cross := config.StageProfile{Model: "gpt-5.4", ModelFamily: "gpt"}
	return &config.Snapshot{
		Effective: config.AgentsRC{
			StageProfiles: map[string]map[string]config.StageProfile{
				"executor": {"default": claude},
				"verifier": {"unit": claude, "cli-runner": claude},
				"reviewer": {
					"architecture-standards":    claude,
					"acceptance-invariants":     claude,
					"adversarial":               claude,
					"cross-harness-adversarial": cross,
				},
			},
			ExecutionProfile: &config.ExecutionProfile{
				ByAppType: map[string]config.AppTypeProfile{
					"go-cli": {
						Topology: config.Topology{VerifierSequence: []string{"unit", "cli-runner"}},
						Lenses:   config.Lenses{LensSet: []string{"architecture-standards", "acceptance-invariants", "adversarial", "cross-harness-adversarial"}},
					},
				},
			},
		},
	}
}

// withPipelineFixture chdirs into a fresh temp repo and stubs appTypeSnapshot to
// the fixture config, restoring both on cleanup.
func withPipelineFixture(t *testing.T, snap func(string) (*config.Snapshot, error)) string {
	t.Helper()
	repo := t.TempDir()
	oldwd, _ := os.Getwd()
	t.Cleanup(func() { _ = os.Chdir(oldwd) })
	if err := os.Chdir(repo); err != nil {
		t.Fatal(err)
	}
	orig := appTypeSnapshot
	t.Cleanup(func() { appTypeSnapshot = orig })
	appTypeSnapshot = snap
	return repo
}

func runPipelineEmit(t *testing.T, jsonOut bool, args ...string) (string, error) {
	t.Helper()
	prev := workflowTestJSON
	workflowTestJSON = jsonOut
	t.Cleanup(func() { workflowTestJSON = prev })
	cmd := newWorkflowPipelineEmitCmd()
	var buf bytes.Buffer
	cmd.SetOut(&buf)
	cmd.SetErr(&buf)
	cmd.SetArgs(args)
	err := cmd.Execute()
	return buf.String(), err
}

func TestPipelineEmitWritesSkeleton(t *testing.T) {
	repo := withPipelineFixture(t, func(string) (*config.Snapshot, error) { return pipelineFixtureSnapshot(), nil })
	out, err := runPipelineEmit(t, false, "--platform", "omp")
	if err != nil {
		t.Fatalf("emit: %v", err)
	}
	if !strings.Contains(out, "wrote") {
		t.Fatalf("output missing wrote line:\n%s", out)
	}
	inner := filepath.Join(repo, ".agents", "workflow", "runtime", "full-loop", "profile-driven.swarm.yaml")
	data, err := os.ReadFile(inner)
	if err != nil {
		t.Fatalf("emitted inner YAML missing: %v", err)
	}
	if !strings.HasPrefix(string(data), "# generated by da workflow pipeline emit; do not hand-edit\n") {
		t.Fatalf("emitted YAML missing generation header:\n%s", string(data)[:80])
	}
	if _, err := os.Stat(filepath.Join(repo, ".agents", "workflow", "runtime", "full-loop", "reconcile.swarm.yaml")); err != nil {
		t.Fatalf("emitted reconcile YAML missing: %v", err)
	}
}

func TestPipelineEmitSpecialized(t *testing.T) {
	repo := withPipelineFixture(t, func(string) (*config.Snapshot, error) { return pipelineFixtureSnapshot(), nil })
	if _, err := runPipelineEmit(t, false, "--platform", "omp", "--app-type", "go-cli"); err != nil {
		t.Fatalf("emit go-cli: %v", err)
	}
	dir := filepath.Join(repo, ".agents", "workflow", "runtime", "full-loop")
	if _, err := os.Stat(filepath.Join(dir, "profile-driven.go-cli.swarm.yaml")); err != nil {
		t.Fatalf("specialized inner YAML missing: %v", err)
	}
	// The canonical skeleton file must NOT be clobbered by a specialized emit.
	if _, err := os.Stat(filepath.Join(dir, "profile-driven.swarm.yaml")); !os.IsNotExist(err) {
		t.Fatalf("specialized emit should not write the canonical skeleton file (err=%v)", err)
	}
}

func TestPipelineEmitDryRunWritesNothing(t *testing.T) {
	repo := withPipelineFixture(t, func(string) (*config.Snapshot, error) { return pipelineFixtureSnapshot(), nil })
	out, err := runPipelineEmit(t, false, "--platform", "omp", "--dry-run")
	if err != nil {
		t.Fatalf("dry-run: %v", err)
	}
	if !strings.Contains(out, "[dry-run] would write") {
		t.Fatalf("dry-run output missing preview:\n%s", out)
	}
	if _, err := os.Stat(filepath.Join(repo, ".agents", "workflow", "runtime", "full-loop")); !os.IsNotExist(err) {
		t.Fatalf("dry-run must not create the runtime dir (err=%v)", err)
	}
}

func TestPipelineEmitJSON(t *testing.T) {
	withPipelineFixture(t, func(string) (*config.Snapshot, error) { return pipelineFixtureSnapshot(), nil })
	out, err := runPipelineEmit(t, true, "--platform", "omp", "--dry-run")
	if err != nil {
		t.Fatalf("json emit: %v", err)
	}
	var res pipelineEmitResult
	if err := json.Unmarshal([]byte(out), &res); err != nil {
		t.Fatalf("json output does not parse: %v\n%s", err, out)
	}
	if res.Platform != "omp" || !res.DryRun || res.Digest == "" || len(res.Artifacts) != 2 {
		t.Fatalf("unexpected json result: %+v", res)
	}
	if res.Artifacts[0].Bytes == 0 {
		t.Fatalf("artifact bytes should be non-zero: %+v", res.Artifacts[0])
	}
}

func TestPipelineEmitMissingPlatform(t *testing.T) {
	withPipelineFixture(t, func(string) (*config.Snapshot, error) { return pipelineFixtureSnapshot(), nil })
	_, err := runPipelineEmit(t, false)
	if err == nil || !strings.Contains(err.Error(), "--platform is required") {
		t.Fatalf("want required-platform error, got %v", err)
	}
}

func TestPipelineEmitUnknownPlatform(t *testing.T) {
	withPipelineFixture(t, func(string) (*config.Snapshot, error) { return pipelineFixtureSnapshot(), nil })
	_, err := runPipelineEmit(t, false, "--platform", "bogus")
	// The enum PreRunE fires first and lists the supported platforms, which the
	// runner's "unknown pipeline platform" message did not.
	if err == nil || !strings.Contains(err.Error(), "--platform must be one of claude-code|omp") {
		t.Fatalf("want unknown-platform error, got %v", err)
	}
}

func TestPipelineEmitClaudeCode(t *testing.T) {
	repo := withPipelineFixture(t, func(string) (*config.Snapshot, error) { return pipelineFixtureSnapshot(), nil })
	out, err := runPipelineEmit(t, false, "--platform", "claude-code")
	if err != nil {
		t.Fatalf("emit claude-code: %v", err)
	}
	if !strings.Contains(out, "wrote") {
		t.Fatalf("output missing wrote line:\n%s", out)
	}
	dir := filepath.Join(repo, ".claude", "workflows")
	for _, name := range []string{"profile-pipeline.mjs", "profile-reconcile.mjs"} {
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatalf("emitted %s missing: %v", name, err)
		}
		if !strings.HasPrefix(string(data), "// generated by da workflow pipeline emit; do not hand-edit\n") {
			t.Fatalf("%s missing generation header:\n%s", name, string(data)[:80])
		}
	}
}

func TestPipelineEmitClaudeCodeSpecialized(t *testing.T) {
	repo := withPipelineFixture(t, func(string) (*config.Snapshot, error) { return pipelineFixtureSnapshot(), nil })
	if _, err := runPipelineEmit(t, false, "--platform", "claude-code", "--app-type", "go-cli"); err != nil {
		t.Fatalf("emit claude-code go-cli: %v", err)
	}
	dir := filepath.Join(repo, ".claude", "workflows")
	if _, err := os.Stat(filepath.Join(dir, "profile-pipeline.go-cli.mjs")); err != nil {
		t.Fatalf("specialized cc pipeline missing: %v", err)
	}
	// The canonical skeleton file must NOT be clobbered by a specialized emit.
	if _, err := os.Stat(filepath.Join(dir, "profile-pipeline.mjs")); !os.IsNotExist(err) {
		t.Fatalf("specialized emit should not write the canonical skeleton file (err=%v)", err)
	}
}

func TestPipelineEmitMissingManifest(t *testing.T) {
	withPipelineFixture(t, func(string) (*config.Snapshot, error) {
		return nil, fmt.Errorf("no %s found at /x", config.AgentsRCFile)
	})
	_, err := runPipelineEmit(t, false, "--platform", "omp")
	if err == nil || !strings.Contains(err.Error(), "no .agentsrc.json in this repo") {
		t.Fatalf("want missing-manifest error, got %v", err)
	}
}

func TestPipelineEmitSnapshotError(t *testing.T) {
	withPipelineFixture(t, func(string) (*config.Snapshot, error) {
		return nil, fmt.Errorf("boom: locked layer missing")
	})
	_, err := runPipelineEmit(t, false, "--platform", "omp")
	if err == nil || !strings.Contains(err.Error(), "boom") {
		t.Fatalf("want passthrough snapshot error, got %v", err)
	}
}

func TestPipelineEmitBadAppType(t *testing.T) {
	withPipelineFixture(t, func(string) (*config.Snapshot, error) { return pipelineFixtureSnapshot(), nil })
	_, err := runPipelineEmit(t, false, "--platform", "omp", "--app-type", "nonexistent")
	if err == nil || !strings.Contains(err.Error(), "no entry for app_type") {
		t.Fatalf("want unknown app_type error, got %v", err)
	}
}

func TestPipelineEmitProjectorError(t *testing.T) {
	withPipelineFixture(t, func(string) (*config.Snapshot, error) { return pipelineFixtureSnapshot(), nil })
	orig := pipelineProjectorFor
	t.Cleanup(func() { pipelineProjectorFor = orig })
	pipelineProjectorFor = func(string) (platform.PipelineProjector, error) {
		return failingPipelineProjector{}, nil
	}

	_, err := runPipelineEmit(t, false, "--platform", "omp")
	if err == nil || !strings.Contains(err.Error(), "projector emit failed") {
		t.Fatalf("want projector emission error, got %v", err)
	}
}

func TestPipelineEmitPlanValidation(t *testing.T) {
	withPipelineFixture(t, func(string) (*config.Snapshot, error) { return pipelineFixtureSnapshot(), nil })
	if _, err := runPipelineEmit(t, false, "--platform", "omp", "--plan", "ghost-plan"); err == nil {
		t.Fatal("a --plan that does not resolve must fail loudly")
	}
}

func TestPipelineEmitMkdirError(t *testing.T) {
	repo := withPipelineFixture(t, func(string) (*config.Snapshot, error) { return pipelineFixtureSnapshot(), nil })
	// A regular file where the .agents directory should be forces MkdirAll to fail.
	if err := os.WriteFile(filepath.Join(repo, ".agents"), []byte("not a dir"), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := runPipelineEmit(t, false, "--platform", "omp")
	if err == nil || !strings.Contains(err.Error(), "create runtime dir") {
		t.Fatalf("want mkdir error, got %v", err)
	}
}

func TestPipelineEmitWriteError(t *testing.T) {
	repo := withPipelineFixture(t, func(string) (*config.Snapshot, error) { return pipelineFixtureSnapshot(), nil })
	// A directory occupying a target filename forces WriteFile to fail while the
	// runtime dir itself already exists.
	outDir := filepath.Join(repo, ".agents", "workflow", "runtime", "full-loop")
	if err := os.MkdirAll(filepath.Join(outDir, "profile-driven.swarm.yaml"), 0o755); err != nil {
		t.Fatal(err)
	}
	_, err := runPipelineEmit(t, false, "--platform", "omp")
	if err == nil || !strings.Contains(err.Error(), "write ") {
		t.Fatalf("want write error, got %v", err)
	}
}

func TestPipelineEmitGetwdError(t *testing.T) {
	prev := osGetwd
	t.Cleanup(func() { osGetwd = prev })
	osGetwd = func() (string, error) { return "", errors.New("no cwd") }
	if _, err := runPipelineEmit(t, false, "--platform", "omp"); err == nil || !strings.Contains(err.Error(), "no cwd") {
		t.Fatalf("want getwd error propagated, got %v", err)
	}
}
