/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: b50606ae6b058693dfb18a36b3defce5)
interface __BaseEnv_Env {
	OBS_DB: D1Database;
	ASSETS: Fetcher;
	OBS_PROJECT_ID: string;
	OBS_AUTH_MODE: string;
	ENVIRONMENT: string;
	PROJECT_DO: DurableObjectNamespace<import("./src/index").ProjectDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ProjectDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OBS_PROJECT_ID" | "OBS_AUTH_MODE" | "ENVIRONMENT">> {}
}
