/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: a1896d0ea97c30586bc69cb455ee3f3a)
interface __BaseEnv_Env {
	OBS_DB: D1Database;
	ASSETS: Fetcher;
	OBS_PROJECT_ID: string;
	ENVIRONMENT: string;
	OBS_AUTH_MODE: string;
	OBS_ACCESS_AUD: string;
	OBS_ACCESS_TEAM_DOMAIN: string;
	PROJECT_DO: DurableObjectNamespace<import("./src/index").ProjectDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ProjectDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OBS_PROJECT_ID" | "ENVIRONMENT" | "OBS_AUTH_MODE" | "OBS_ACCESS_AUD" | "OBS_ACCESS_TEAM_DOMAIN">> {}
}
